server:
  port: 1990

spring:
  application:
    name: sirius-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 43.138.34.9:8848
    gateway:
      discovery:
        locator:
          # 让gateway从nacos中获得服务信息
          enabled: true
      # 路由：routes[数组结构] 当求情满足什么样的条件的时候转发到哪个微服务
      routes:
        - id: sirius-demo
          # lb:负载均衡的标识，后面跟服务名称
          uri: lb://sirius-demo
          order: 1
          predicates:
              - Path=/demo/**
          filters:
            - StripPrefix=1

        - id: sirius-gaodeditu
          uri: lb://sirius-gaodeditu
          order: 1
          predicates:
            - Path=/gaodeditu/**
          filters:
            - StripPrefix=1




