server:
  port: 1997
  servlet:
    context-path: /

spring:
  datasource:
    username: root
    password: tianlangxing
    url: jdbc:mysql://47.103.18.191:3306/dts-demo?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver