server:
  port: 1997
  servlet:
    context-path: /sirius-demo

spring:
  application:
    name: sirius-demo
  datasource:
    username: root
    password: tianlangxing
    url: jdbc:mysql://43.138.34.9:3306/dts-demo?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: 43.138.34.9:8848
    sentinel:
      transport:
        # 跟控制台交流的端口，随意指定一个未使用的端口
        port: 3000
        # sentinel控制台的服务地址
        dashboard: localhost:8080

  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0

# mybatis-plus配置信息
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true  #开启驼峰功能
  mapper-locations: classpath*:mybatis/**/*Mapper.xml